#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

if [ "$1" == "K" ]; then
  # run synchronously
  {
    for i in /etc/rc.d/$1*; do
      $i $2 2>&1
    done 
  } | logger -s -p 6 -t ''
else
  # Run asynchronously
  {
    for i in /etc/rc.d/$1*; do
      $i $2 2>&1
    done 
  } | logger -s -p 6 -t '' &
fi
