#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=36
start() {
	if [ -c /dev/watchdog ]; then
		watchdog -t 5 /dev/watchdog
	elif [ -c /dev/misc/watchdog ]; then
		watchdog -t 5 /dev/misc/watchdog
	fi
}
